#!/bin/sh
PROGRAM=${PWD##*/}

NREPEATS=10
NPEELS=10
NPOLYGONS=100
OPACITY=0.1
COLOR=(255 0 0)
BACKGROUND=(255 255 255)

./$PROGRAM -nrepeats $NREPEATS -npeels $NPEELS -npolygons $NPOLYGONS -opacity $OPACITY -color ${COLOR[0]} ${COLOR[1]} ${COLOR[2]} -background ${BACKGROUND[0]} ${BACKGROUND[1]} ${BACKGROUND[2]}
